config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :examinations do 
    collection do      get :create_exam
      post :insert_exam
      get :insert_mark
      get :insert
      get :exam
      post :save_test
      get :question_paper
      post :save_test
      get :apply_exam
      get :publish_result
      get :display_result
      post :qualify_student
      get :qualified_student
       get :select_question_type
      get :option
      get :disp_time
    end
    member do
      get :show_question
    end
   
      resources :exam_questions
  end

  resources :exams
  get 'exam_questions/index'

  get 'exam_questions/new'

  resources :sub_courses
  get 'enquiries/index'

  get 'enquiries/create'

  

  resources :payments do
    member do
    get :show_payment
      get :confirm_to_pay
  end
end




  resources :exam_answers

  resources :sub_courses
  resources :queries do
    resources :answers
  end
  resources :enquiries
  resources :answers
  resources :question_types
  resources :coupon_courses
  resources :courses do

    collection do
      get :student_courses
    end
  end
  resources :reports do 
    collection do
      get :select, :report, :reference_report , :select_reference
    end
  end

  resources :courses do
    resources :coupons
  end
  resources :coupons
  resources :students do 
  end
  resources :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  as :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
        get 'sign_in' => 'devise/sessions#new'

      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :admins, :skip => :sessions
  root 'home#dashboard'

  resources :home do
        collection do
          get :dashboard
          get 'about'
          get 'index'
          get 'contact'
          get 'courses'
          get 'login'
          get 'blog'
          get 'register'
          get 'our_team'
          get 'course1'
          
        end
      end


  resources :users do
     member do
      get :change_password
      patch :update_password
    end
  end

    match '/payu_callback' => 'payments#payu_return', :via => [:get, :post], :as => 'payments_payu_return' 
        
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
	  belongs_to :question
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :course
end

app/models/coupon.rb
class Coupon < ApplicationRecord
	  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
 has_many :coupons, dependent: :destroy
 has_many :payments
   scope :load, ->(id) { where(id: id).take }

 has_attached_file :photo
 validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/jpg']
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
	 has_many :questions, :dependent => :destroy
     accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }
end

app/models/exam_answer.rb
class ExamAnswer < ApplicationRecord
  belongs_to :exam_question
end

app/models/examination.rb
class Examination < ApplicationRecord
	has_many :exam_questions
  accepts_nested_attributes_for :exam_questions, allow_destroy: true
  has_many :weightages
  scope :load, ->(id) { where(id: id).take }

   def self.calculateres(test, exam, student)
    final_res = []
    question_types = []
    tot_question_types = []
    StudentExam.create(examination_id: exam,
                       student_id: student.id)
    student_exam = StudentExam.where(student_id: student).take
    i = 0
    test.each do |key, value|
      StudentAnswerSheet.create(student_exams_id: student_exam.id,
                                exam_questions_id: key,
                                options_id: value)
        ans = Option.where(exam_question_id: key.to_i, id: value.to_i).take

      if ans.is_answer == 't'
        i += 1
        question_types << ans.exam_question
    end
  end
   result = Examination.tot_per(question_types, exam)
    final_res << result
    StudentScore.create(examination_id: exam,
                        student_id: student.id, score: i.to_f)
    score = StudentScore.where(student_id: student.id,
                               examination_id: exam).take
    final_res << score.score
    final_res
  end

  # percentage
  def self.tot_per(question_types, exam)
    
    result = []
    types = Weightage.where(examination_id: exam)
    types.each do |r|
     
      total = r.examination.total_marks_of_question.to_f
      ans = question_types.length.to_f
      if total == 0
        per = 0
      else
        per = ((ans*2) * 100 / total)
      end
      result << [r.examination.exam_name, per]
    end
    result
  end
end

app/models/home.rb
class Home < ApplicationRecord

	 attr_accessor :name, :email, :contact_no,:message

  validates :name,
    presence: true

  validates :email,
    presence: true

 
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :exam_question
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student, optional:true
  belongs_to :course, optional:true
  belongs_to :coupon, optional:true
  scope :shod, ->(id) { where(id: id).take }
  scope :list1, -> { where(payment_status: 'Offline') }
  scope :list2, ->  { where(payment_status: 'Online') }
end

app/models/query.rb
class Query < ApplicationRecord
	has_many :answers
	belongs_to :user, optional:true
	belongs_to :student , optional:true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :exam
	has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :payments	
	has_many :queries
	has_many :users
	belongs_to :course, optional:true
    scope :load, ->(id) { where(id: id).take } #  	def self.set_referral_code
 #     self.name[0..2] += rand(0..10000).to_s

 # end
end

app/models/sub_course.rb
class SubCourse < ApplicationRecord
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   scope :role_wise_users, ->(role) { where(role: role) }
   validates :phone_no, numericality: { only_integer: true }, length: \
  { minimum: 10, maximum: 10 }, allow_blank: true
  belongs_to :student, optional:true
  scope :shod, ->(id) { where(id: id).take }
  has_many :queries
  belongs_to :student, optional:true
  

 def create_general_setting
    role = 'Student'
    role = 'SuperAdmin' if id == 1
    gs = GeneralSetting.create(name: 'Portal')
    update(general_setting_id: gs.id, role: role)
  end

 def self.current
    Thread.current[:user]
  end

   def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # setter for current user
  def self.current=(user)
    Thread.current[:user] = user
  end

  # def student_name
  #   [firstname, middlename, lastname].join(' ')
  #  end

end

app/models/weightage.rb
class Weightage < ApplicationRecord
  belongs_to :examination, optional:true
  belongs_to :question_type, optional:true
  belongs_to :placement_exam, optional:true
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/_form.html.erb
    <div class="span12">
      <div class="widget-box">
        <div class="widget-title">
         <span class="icon"> <i class="icon-align-justify"></i> </span>
        </div>
        <div class="widget-content nopadding">
        <div class="form-horizontal"">
<%= form_with(model: admin, local: true) do |form| %>
  
              <div class="control-group">
              <label class="control-label">Admin Name :</label>
              <div class="controls">
              <%= form.text_field :name,class: "form-control", id: :admin_name %>

<!--                 <input type="text" class="form-control" placeholder="Enter Name" />
 -->              </div>
            </div>
<!-- <div class="section">
                <label class="input">User Name <i class="icon-append fa fa-user"></i>
                  <%#= form.text_field :name, id: :admin_name %></label>
                  </div> -->
  <!-- <div class="field">
    <%#= form.label :name %>
    <%#= form.text_field :name, id: :admin_name %>
  </div>
 -->
              <div class="control-group">
              <label class="control-label">Email :</label>
              <div class="controls">
              <%= form.text_field :email,class: "form-control", id: :admin_email %>

<!--                 <input type="text" class="form-control" placeholder="Enter Name" />
 -->              </div>
            </div>
 <!-- <div class="section">
                <label class="input">Email <i class="icon-append fa fa-envelope-o"></i>
                   <%#= form.text_field :email, id: :admin_email %>
                  </label>
              </div> -->
  <!-- <div class="field">
    <%#= form.label :email %>
    <%#= form.text_field :email, id: :admin_email %>
  </div> -->
              <div class="control-group">
              <label class="control-label">Phone Number :</label>
              <div class="controls">
              <%= form.text_field :phonenumber,class: "form-control", id: :phonenumber %>

<!--                 <input type="text" class="form-control" placeholder="Enter Name" />
 -->              </div>
            </div>
<!-- 
   <div class="section">
        <label class="input">Phone Number<i class="icon-append fa fa-lock"></i>
        <%#=form.text_field :phonenumber, id: :phonenumber %>
        </label>
        </div> -->
  <!-- <div class="field">
    <%#= form.label :phone_number %>
    <%#= form.number_field :phonenumber, id: :admin_phonenumber %>
  </div> -->


  <div class="widget-content nopadding">
          <form action="#" method="get" class="form-horizontal">
            <div class="control-group">
              <label class="control-label">Password :</label>
              <div class="controls">
              <%= form.password_field :password,class: "form-control", id: :admin_password %>

<!--                 <input type="text" class="form-control" placeholder="Enter Name" />
 -->              </div>
            </div>

 <!--  <div class="section">
              <label class="input">Password <i class="icon-append fa fa-lock"></i>
              <%#= form.text_field :password, id: :admin_password %> </label>
              </div> -->
              <!-- <div class="field">
    <%#= form.label :password %>
    <%#= form.text_field :password, id: :admin_password %>
  </div> -->


<div class="widget-content nopadding">
          <form action="#" method="get" class="form-horizontal">
            <div class="control-group">
              <label class="control-label">Conform Password :</label>
              <div class="controls">
              <%= form.password_field :confirm_password,class: "form-control", id: :admin_confirm_password %>

<!--                 <input type="text" class="form-control" placeholder="Enter Name" />
 -->              </div>
            </div>
<!--             
     <div class="section">
              <label class="input">Confirm Password <i class="icon-append fa fa-lock"></i>
              <%#= form.text_field :confirm_password, id: :admin_confirm_password %> </label>
              </div>
 -->
  <!-- <div class="field">
    <%#= form.label :confirm_password %>
    <%#= form.text_field :confirm_password, id: :admin_confirm_password %>
  </div> -->

 
  <div class="form-actions">
     <button type="submit" class="btn btn-success">Create Admin </button>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>
  <h1>Admins</h1>
<div class="container-fluid">
  <hr>  
    
    <div class="widget-content nopadding">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <tr class="odd gradeX">
            <th>Sr. No.</th>
             <th>Name</th>
             <th>Email</th>
             <th>Phonenumber</th>
             <th>Password</th>
             <th>Confirm password</th>
             <th colspan="3"></th>
            </tr>
            </tr>
        </thead>
        <tbody>
          <% @admins.each_with_index do |admin, i| %>
            <tr>
              <td><%= i+1%></td>
              <td><%= admin.name %></td>
              <td><%= admin.email %></td>
              <td><%= admin.phonenumber %></td>
              <td><%= admin.password %></td>
              <td><%= admin.confirm_password %></td>
              <td><%= link_to 'Show', admin, class: "btn btn-primary" %></td>
              <td><%= link_to 'Edit', edit_admin_path(admin), class: "btn btn-warning" %></td>
              <%#= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
            </tr>
            <% end %>
        </tbody>
        </table>
        </div>

      <br>
      <%= link_to 'New Admin', new_admin_path, class: "btn btn-success" %>
</div>
</div>

app/views/admins/new.html.erb
<%=render 'form',  admin: @admin%>

app/views/admins/show.html.erb
<div class="span6">
        <div class="widget-box widget-chat">
          <div class="widget-title bg_lb"> <span class="icon"> <i class="icon-comment"></i> </span>
            <h5>Admin Details</h5>
          </div>
          <div class="widget-content collapse in" id="collapseG4">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @admin.phonenumber %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<p>
  <strong>Confirm password:</strong>
  <%= @admin.confirm_password %>
</p>

<p>
  <strong>Referral Code:</strong>
  <%= @admin.admin_referral_code %>
</p>
</div>
</div>
<%= link_to 'Edit', edit_admin_path(@admin), class: "btn btn-sucess" %> |
<%= link_to 'Back', admins_path, class: "btn btn-denger" %>