config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :examinations do 
    collection do      get :create_exam
      post :insert_exam
      get :insert_mark
      get :insert
      get :exam
      post :save_test
      get :question_paper
      post :save_test
      get :apply_exam
      get :publish_result
      get :display_result
      post :qualify_student
      get :qualified_student
       get :select_question_type
      get :option
      get :disp_time
    end
    member do
      get :show_question
    end
   
      resources :exam_questions
  end

  resources :exams
  get 'exam_questions/index'

  get 'exam_questions/new'

  resources :sub_courses
  get 'enquiries/index'

  get 'enquiries/create'

  

  resources :payments do
    member do
    get :show_payment
      get :confirm_to_pay
  end
end




  resources :exam_answers

  resources :sub_courses
  resources :queries do
    resources :answers
  end
  resources :enquiries
  resources :answers
  resources :question_types
  resources :coupon_courses
  resources :courses do

    collection do
      get :student_courses
    end
  end
  resources :reports do 
    collection do
      get :select, :report, :reference_report , :select_reference
    end
  end

  resources :courses do
    resources :coupons
  end
  resources :coupons
  resources :students do 
  end
  resources :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  as :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
        get 'sign_in' => 'devise/sessions#new'

      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :admins, :skip => :sessions
  root 'home#dashboard'

  resources :home do
        collection do
          get :dashboard
          get 'about'
          get 'index'
          get 'contact'
          get 'courses'
          get 'login'
          get 'blog'
          get 'register'
          get 'our_team'
          get 'course1'
          
        end
      end


  resources :users do
     member do
      get :change_password
      patch :update_password
    end
  end

    match '/payu_callback' => 'payments#payu_return', :via => [:get, :post], :as => 'payments_payu_return' 
        
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :exam_question
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:option, :is_answer, :exam_questions_id)
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_with(model: option, local: true) do |form| %>
  <% if option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :option %>
    <%= form.text_field :option, id: :option_option %>
  </div>

  <div class="field">
    <%= form.label :is_answer %>
    <%= form.text_field :is_answer, id: :option_is_answer %>
  </div>

  <div class="field">
    <%= form.label :exam_questions_id %>
    <%= form.text_field :exam_questions_id, id: :option_exam_questions_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing Option</h1>

<%= render 'form', option: @option %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Options</h1>

<table>
  <thead>
    <tr>
      <th>Option</th>
      <th>Is answer</th>
      <th>Exam questions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.option %></td>
        <td><%= option.is_answer %></td>
        <td><%= option.exam_questions %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New Option</h1>

<%= render 'form', option: @option %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Option:</strong>
  <%= @option.option %>
</p>

<p>
  <strong>Is answer:</strong>
  <%= @option.is_answer %>
</p>

<p>
  <strong>Exam questions:</strong>
  <%= @option.exam_questions %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>