config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :examinations do 
    collection do      get :create_exam
      post :insert_exam
      get :insert_mark
      get :insert
      get :exam
      post :save_test
      get :question_paper
      post :save_test
      get :apply_exam
      get :publish_result
      get :display_result
      post :qualify_student
      get :qualified_student
       get :select_question_type
      get :option
      get :disp_time
    end
    member do
      get :show_question
    end
   
      resources :exam_questions
  end

  resources :exams
  get 'exam_questions/index'

  get 'exam_questions/new'

  resources :sub_courses
  get 'enquiries/index'

  get 'enquiries/create'

  

  resources :payments do
    member do
    get :show_payment
      get :confirm_to_pay
  end
end




  resources :exam_answers

  resources :sub_courses
  resources :queries do
    resources :answers
  end
  resources :enquiries
  resources :answers
  resources :question_types
  resources :coupon_courses
  resources :courses do

    collection do
      get :student_courses
    end
  end
  resources :reports do 
    collection do
      get :select, :report, :reference_report , :select_reference
    end
  end

  resources :courses do
    resources :coupons
  end
  resources :coupons
  resources :students do 
  end
  resources :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  as :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
        get 'sign_in' => 'devise/sessions#new'

      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :admins, :skip => :sessions
  root 'home#dashboard'

  resources :home do
        collection do
          get :dashboard
          get 'about'
          get 'index'
          get 'contact'
          get 'courses'
          get 'login'
          get 'blog'
          get 'register'
          get 'our_team'
          get 'course1'
          
        end
      end


  resources :users do
     member do
      get :change_password
      patch :update_password
    end
  end

    match '/payu_callback' => 'payments#payu_return', :via => [:get, :post], :as => 'payments_payu_return' 
        
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student, optional:true
  belongs_to :course, optional:true
  belongs_to :coupon, optional:true
  scope :shod, ->(id) { where(id: id).take }
  scope :list1, -> { where(payment_status: 'Offline') }
  scope :list2, ->  { where(payment_status: 'Online') }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def index
	    @payments = Payment.all	
	    @students = Student.all
	end

	def new
		@payment = Payment.new
		@course = Course.find(params[:format])
	end

	def create
		@payment = Payment.new(payment_params)
    @course = Course.load(params[:id])
		fees1 = params[:instalment]
		fees2 = params[:remaining]
    full_fees = params[:fees]
		@payment.save
		@payment.update!(instalment: fees1, remaining: fees2, student_id: current_user.student.id, fees: full_fees)

		redirect_to @payment
	end

	def confirm_to_pay
     @payment = Payment.find(params[:id])
     @student = current_user.student
     @payment.update_attributes(txnid: SecureRandom.hex(10))
     @payment = @student.payments.build(
        txnid: @payment.txnid,
        course_id: @payment.course_id,
        amount: @payment.instalment,
        email: current_user.student.email,
        status: 'will send request for payment'
      )
    @payment.save
  end

  def payu_return                                              
      notification = PayuIndia::Notification.new(request.query_string, options = {:key => 'gtKFFx', :salt => 'eCwWELxi', :params => params})    
      payment = Payment.find_by(txnid: notification.invoice)  # invoice is nothing but the payment_id
      if notification.params["status"] == "success"
        payment.status = params[:status]
        payment.unmappedstatus = params[:unmappedstatus]
        # payment.ip = request.remote_ip
        payment.name_on_card  = params[:name_on_card]
        payment.issuing_bank = params[:issuing_bank]
        payment.cardCategory = params[:card_type]
        payment.payment_mode = 'online'
        if payment.save
          @payment = payment
          flash[:notice] = "Payment Done successfully!!!"
          redirect_to payment
        end
      else
        flash[:notice] = "Payment fail!. Please try again"
        redirect_to payment    #show.html.erb
      end
    # rescue
    #   flash[:notice] = "something goes wrong ! please try again after some times!!!"
    #   redirect_to customer_path(current_user)
    # end
  end

	def show
		@payment = Payment.find(params[:id])
          respond_to do |format|
   		  format.html
   		  format.pdf do
       	render pdf: "show_payment.pdf.erb"   # Excluding ".pdf" extension.
     	end
   	  end
    end



    def show_payment
    	@payment = Payment.find(params[:id])
          respond_to do |format|
   		  format.html
   		  format.pdf do
       	render pdf: "show_payment.pdf.erb"   # Excluding ".pdf" extension.
     	end
   	  end
    end
	private

	def payment_params
		params.require(:payment).permit!
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/confirm_to_pay.html.erb
    <br/><h3><center>Confirm Payment</center></h3><br/>
    <table cellpadding="5" cellspacing="5" width="700">
      <tr><th colspan="3" bgcolor="99CCFF" align="left">Student Profile</th></tr>
    
<tr>
 <td>

    <strong>Student Name:</strong>
    <%= current_user.firstname%>
</td>
<td>
<strong>Address:</strong>
<%= current_user.student.address%>
</td>

<td>
<strong>Phone no:</strong>
<%= current_user.student.phone_number%>
</td>

<td>
  <strong>To Pay:</strong>
  <%= @payment.amount.to_i %>
</td>
<td>
<strong>Email</strong>
<%=@current_user.email%>
</td>



<td>
  <strong>Token:</strong>
<%= text_field_tag :access_token,"", value: @payment.txnid, readonly:true%>
</td>

      </tr>
    </table>


 <br>

  <% payment_form_for_payu 'gtKFFx', 'eCwWELxi', 
            :txnid => @payment.txnid,
            :amount => @payment.amount.to_i,
            :productinfo => 'Fees Payment',
            :firstname => @payment.student.name,
            :email => @payment.student.email,
            :phone =>  @payment.student.phone_number,
            :surl => 'http://' + "localhost" + ':3000/payu_callback',
            :furl => 'http://' + "localhost" + ':3000/payu_callback',
            :html => { :id => 'payment-form' } %>
         

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Remaning</th>
        <th>To Pay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.remaining %></td>
        
          <td><%= payment.instalment %></td>
          <td><%= link_to 'Download PDF ',show_payment_payments_path(payment, format: 'pdf'),target: '_blank', class: "btn btn-primary"%> </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/payments/new.html.erb
<h4>Payment Details</h4>
<div class="row-fluid">
    <div class="span12">
      <div class="widget-box">
        <div class="widget-title">
         <span class="icon"> <i class="icon-align-justify"></i> </span>
        </div>
        <div class="widget-content nopadding">
        <div class="form-horizontal"">
<%= form_for @payment, url:{action: 'create', controller: 'payments'} do |form| %>
              <%= hidden_field_tag 'course_id', @course.id %>
              <div class="control-group">
              <label class="control-label">Payment mode :</label>
              <div class="controls">
              <%= form.radio_button  "payment_status","Online" %>&nbsp;&nbsp;<b>Online</b>&nbsp;&nbsp;
              <%= form.radio_button  "payment_status","Offline"%>&nbsp;&nbsp;<b>Offline</b>
<!--                 <input type="text" class="span11" placeholder="Enter Name" />
 -->              </div>
<!-- <div class="section">
                <label class="input">User Name <i class="icon-append fa fa-user"></i>
                  <%#= form.text_field :name, id: :admin_name %></label>
                  </div> -->
  <!-- <div class="field">
    <%#= form.label :name %>
    <%#= form.text_field :name, id: :admin_name %>
  </div>
 -->
              <div class="control-group">
              <label class="control-label">Payment Type:</label>
              <div class="controls">
              <%= form.radio_button  "payment_type","Fulpayment",:id => "payment_type2" %>&nbsp;&nbsp;<b>Full Payment</b>&nbsp;&nbsp;
              <%= form.radio_button  "payment_type","Installment",:id => "payment_type1"%>&nbsp;&nbsp;<b>Installment</b>

<!--                 <input type="text" class="span11" placeholder="Enter Name" />
 -->              </div>
            </div>
 


</div>
</div>
</div>
</div>
</div>
<p>
<strong>Student Name :</strong>
<%= current_user.firstname %>
</p>
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <hr>
    <div class="widget-content nopadding">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
          <th>Course name</th>
          <th>Course validity</th>
          <th>Admission start date</th>
          <th>Admission end date</th>
          <th>Fees</th>
          <th>Installment Fees</th>
          <th>Remaining Fees</th>
          <th colspan="3"></th>
          </tr>
        </thead>
      <tbody>
    <%# @courses.each do |course| %>
        <%#if course.course_validity == Date.today%>
        <%# course.status = 'false' %>
        <%#course.update!(status: 'false')%>
          <%#end%>
          
      <tr class="odd gradeX">

        <tr>
          <td><%= @course.course_name %></td>
          <td><%= @course.course_validity %></td>
          <td><%= @course.admission_start_date %></td>
          <td><%= @course.admission_end_date %></td>
          <td><%= text_field_tag :fees ,"",value: @course.fees, id: :fees,class: 'form-control' %></td>

          <td><%= text_field_tag :instalment ,"", id: :instalment_fees,class: 'form-control' %></td>
           <td><%= text_field_tag :remaining ,"", id: :remaining_fees,class: 'form-control' %></td>
        </tr>
  </tbody>
</table>

<br>
 
  <div class="form-actions">
     <%=form.submit class: 'btn btn-success'%>
  </div>

</tr>
</tbody>
</table>
</div>

<% end %>

<script type="text/javascript">
  $("#payment_type1").on("change", function() {
    var d = $('#fees').val()/2;
    $('#remaining_fees').val(d);
    $('#instalment_fees').val(d);
  });
</script>

<script type="text/javascript">
  $("#payment_type2").on("change", function() {
    var d = $('#fees').val() - $('#fees').val();
    $('#remaining_fees').val(d);
    $('#instalment_fees').val(d);
  });
</script>

app/views/payments/show.html.erb
<div class="span6">
        <div class="widget-box widget-chat">
          <div class="widget-title bg_lb"> <span class="icon"> <i class="icon-money"></i> </span>
            <h5>Admin Details</h5>
          </div>
          <div class="widget-content collapse in" id="collapseG4">
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>

<p>
	<strong>Student Name:</strong>
	<%= current_user.firstname%>
</p>
<p>
<strong>Address:</strong>
<%= current_user.student.address%>
</p>

<p>
<strong>Phone no:</strong>
<%= current_user.student.phone_number%>
</p>

<%if @payment.payment_type == 'Installment'%>
<p>

  <strong>Remaning:</strong>
  <%= @payment.remaining %>
</p>

<p>
  <strong>To Pay:</strong>
  <%= @payment.instalment %>
</p>

<%else%>
<p>
<strong>Fees</strong>

<%=@payment.fees%>
</p>

<%end%>




<td><%= link_to 'Download PDF ',show_payment_payment_path(@payment, format: 'pdf'),target: '_blank', class: "btn btn-success"%> </td>
<%if @payment.payment_status == 'Online'%>                                                                                                                                                                         
<%= link_to "Confirm To Pay", confirm_to_pay_payment_path(@payment.id), class: 'btn btn-warning'%>
<%end%>

app/views/payments/show_payment.pdf.erb
<!DOCTYPE html>
<html>
<head>
<style>
.clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  color: #5D6975;
  text-decoration: underline;
}


body {
  position: relative;
  width: 21cm;  
  height: 29.7cm; 
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 14px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 200px;
}

h1 {
  border-top: 1px solid  #5D6975;
  border-bottom: 1px solid  #5D6975;
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
  background: url(/assets/dimension.png);
}



table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}

table tr:nth-child(2n-1) td {
  background: #F5F5F5;
}

table th,
table td {
  text-align: center;
}

table th {
  padding: 5px 20px;
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}
</style>

</head>

  <body>
    <div class="center"><h2><b><font color="grey"><%= raw "#{@payment.payment_type}" if @payment.present?  %>
  </font></b></h2></div>
<header class="clearfix">
      <div id="logo">
         <%= wicked_pdf_image_tag('logo.png') %>
      </div>
      <br><br>
      
      <h1>Payment Receipt</h1>

      <div id="company" class="clearfix">
        <div>Name :<%= current_user.firstname%></div>
        <div>Address :<%= current_user.student.address%></div>
        <div>Phon. No. :<%= current_user.student.phone_number%></div>
      </div>
<br><br><br><br>
<body>



<table class="table table-condensed table-bordered" style="margin-top: -15px; margin-bottom: 15px;">
              <thead>
                <tr>
                  <th style="font-size: 16px; background-color: #ccc; width: 75px;" colspan="11"><center>Payment Recipts</center></th>
                  </tr>
                <th>Name :</th>
                <th>Address :</th>
                <th>Total Amount</th>

                <tr>
                <td><%= current_user.firstname%></td>
                <td><%= current_user.student.address%></td>
            <%if @payment.payment_type == 'Installment'%>
                
                <td><%= @payment.instalment %></td>
            <%else%>
                <td><%= @payment.fees %></td>    
              <%end%>

                 <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
  	
<table class="table table-condensed table-bordered" style="margin-top: -15px; margin-bottom: 15px;">
  <thead>
  <br>

    <tr>
      <th> 
        <H2 align="right">For <%=current_user.firstname%></H2>
        <h2 align="right">&nbsp;</h2>
        <h2 align="right">Authorized Signatory</h2> 
      </th>
    </tr>
  </thead>
</table>

    </body>
    </html>