config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :examinations do 
    collection do      get :create_exam
      post :insert_exam
      get :insert_mark
      get :insert
      get :exam
      post :save_test
      get :question_paper
      post :save_test
      get :apply_exam
      get :publish_result
      get :display_result
      post :qualify_student
      get :qualified_student
       get :select_question_type
      get :option
      get :disp_time
    end
    member do
      get :show_question
    end
   
      resources :exam_questions
  end

  resources :exams
  get 'exam_questions/index'

  get 'exam_questions/new'

  resources :sub_courses
  get 'enquiries/index'

  get 'enquiries/create'

  

  resources :payments do
    member do
    get :show_payment
      get :confirm_to_pay
  end
end




  resources :exam_answers

  resources :sub_courses
  resources :queries do
    resources :answers
  end
  resources :enquiries
  resources :answers
  resources :question_types
  resources :coupon_courses
  resources :courses do

    collection do
      get :student_courses
    end
  end
  resources :reports do 
    collection do
      get :select, :report, :reference_report , :select_reference
    end
  end

  resources :courses do
    resources :coupons
  end
  resources :coupons
  resources :students do 
  end
  resources :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  as :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
        get 'sign_in' => 'devise/sessions#new'

      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :admins, :skip => :sessions
  root 'home#dashboard'

  resources :home do
        collection do
          get :dashboard
          get 'about'
          get 'index'
          get 'contact'
          get 'courses'
          get 'login'
          get 'blog'
          get 'register'
          get 'our_team'
          get 'course1'
          
        end
      end


  resources :users do
     member do
      get :change_password
      patch :update_password
    end
  end

    match '/payu_callback' => 'payments#payu_return', :via => [:get, :post], :as => 'payments_payu_return' 
        
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
  end

  def student_courses
    @courses = Course.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_name, :fees, :course_description, :course_validity, :status, :batch, :admission_start_date, :admission_end_date, :coupon_id, :photo)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
    <div class="span10">
      <div class="widget-box">
        <div class="widget-title">
         <span class="icon"> <i class="icon-align-justify"></i> </span>
          <h5>New Course</h5>
        </div>
        <div class="widget-content nopadding">
        <div class="form-horizontal"">
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="control-group">
  <label class="control-label">Course Name :</label>
    <div class="controls">
    <%= form.text_field :course_name, class: "form-control",id: :course_course_name %>
    </div>
  </div>
  <!--          <input type="text" class="form-control" placeholder="Enter Name" />
  -->    
  <div class="control-group">
  <label class="control-label">Course Description :</label>
    <div class="controls">
    <%= form.text_field :course_description,class: "form-control",id: :course_course_description %>
    </div>
  </div>

  <div class="control-group">
  <label class="control-label">Course Validity :</label>
    <div class="controls">
    <%= form.date_field :course_validity,value: Date.today,class: "datepicker", id: :course_course_validity ,remote: true%>

  <!--          <input type="text" class="form-control" placeholder="Description" />
  -->              </div>
  </div>

  <div class="control-group">
  <label class="control-label">Course Fees :</label>
    <div class="controls">
    <%= form.text_field :fees,class: "form-control", id: :course_fees %>
  <!--          <input type="text" class="form-control" placeholder="Description" />
  -->              </div>
  </div>


  <div class="control-group">
  <label class="control-label">Upload Course Image :</label>
  <div class="controls">
  <%=form.file_field :photo, class: "form-control"%>
  <!--          <input type="text" class="form-control" placeholder="Description" />
  -->              </div>
  </div>

  <div class="control-group">
  <label class="control-label">Course Status :</label>
    <div class="controls">
    <p>
    <%= form.radio_button :status, 'Active' %> Active <br />
    <%= form.radio_button :status, 'Inactive' %> Inactive<br />
      </p>
  <!--          <input type="text" class="form-control" placeholder="Description" />
  --> </div>


  <!-- <div class="field">
  <%#= form.label :status %>
  <%#= form.text_field :status, id: :course_status %>
  </div> -->
  <!-- <div class="control-group">
  <label class="control-label">Course Batch :</label>
  <div class="controls">
  <%#= form.text_field :batch, id: :course_batch %>
  <!--          <input type="text" class="form-control" placeholder="Description" />
  -->             

  <div class="control-group">
  <label class="control-label">Admission Start Date :</label>
    <div class="controls">
    <%= form.date_field :admission_start_date,class: "datepicker", id: :course_admission_start_date %>
  <!--          <input type="text" class="form-control" placeholder="Description" />
  -->              </div>
  </div>
  <div class="control-group">
  <label class="control-label">Admission End Date :</label>
    <div class="controls">
    <%= form.date_field :admission_end_date,class: "datepicker", id: :course_admission_end_date %>
  <!--          <input type="text" class="form-control" placeholder="Description" />
  -->              </div>
  </div>
  <div class="form-actions">
     <%= form.submit "Create Course" ,class: "btn btn-success"%>
  </div>
<% end %>

<script type="text/javascript">
  $('.datepicker').datepicker();
  $('#datetimepicker1').datetimepicker();
</script>

app/views/courses/edit.html.erb
<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Course</h1>
<div class="container-fluid">
  <hr>

<div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
      <th>Sr.No </th>            
      <th>Course name</th>
      <th>Course description</th>
      <th>Course validity</th>
      <!-- <th>Status</th> -->
      <th>Admission start date</th>
      <th>Admission end date</th>
       <th>Fees</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each_with_index do |course, i| %>
    <%if course.course_validity == Date.today%>
    <% course.status = 'false' %>
    <%course.update!(status: 'false')%>
    <%end%>
      <tr>
        <td><%= i+1 %></td>
        <td><%= course.course_name %></td>
        <td><%= course.course_description %></td>
        <td><%= course.course_validity %></td>
        <!-- <td><%= course.status %></td> -->
        <td><%= course.admission_start_date %></td>
        <td><%= course.admission_end_date %></td>
         <td><%= course.fees %></td>
        <td><%= link_to 'Show', course, class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_course_path(course), class: "btn btn-warning"%></td>
<!--         <td><%#= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 -->      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Course', new_course_path, class: "btn btn-success" %>
</tr>
</tbody>
</table>
</div>
  
  <div class="widget nopadding">
  <ul class="pager">
  <li><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">4</a></li>
  <li><a href="#">5</a></li>
</ul>
</div>

app/views/courses/new.html.erb
<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<div class="span6">
        <div class="widget-box widget-chat">
          <div class="widget-title bg_lb"> <span class="icon"> <i class="icon-comment"></i> </span>
            <h5>Course Details</h5>
          </div>
          <div class="widget-content collapse in" id="collapseG4">
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @course.course_name %>
</p>

<p>
  <strong>Course description:</strong>
  <%= @course.course_description %>
</p>

<p>
  <strong>Course validity:</strong>
  <%= @course.course_validity %>
</p>

<p>
  <strong>Course Fees</strong>
  <%= @course.fees %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.status %>
</p>
<p>


<%= image_tag @course.photo.url %>
</p>


<p>
  <strong>Batch:</strong>
  <%= @course.batch %>
</p>

<p>
  <strong>Admission start date:</strong>
  <%= @course.admission_start_date %>
</p>

<p>
  <strong>Admission end date:</strong>
  <%= @course.admission_end_date %>
</p>
</div>
</div>
</div>

        

<div class="widget-box">
  <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
    <h5>ADD COUPON</h5>
      </div>
      <div class="widget-content nopadding">
<%=render 'coupons/form'%> 
<br>

<h3>COUPON DETAILS</h3> 
<%= render 'coupons/coupon'%>      
</div>
</div>
</div>

app/views/courses/student_courses.html.erb
<p id="notice"><%= notice %></p>
<h1>Course</h1>
<div class="container-fluid">
  <hr>
    <div class="widget-content nopadding">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
          <th>Course name</th>
          <th>Course description</th>
          <th>Course validity</th>
<!--           <th>Status</th>
 -->          <th>Batch</th>
          <th>Admission start date</th>
          <th>Admission end date</th>
          <th>Fees</th>
          <th colspan="3"></th>
          </tr>
        </thead>
      <tbody>
    <% @courses.each do |course| %>
        <%if course.course_validity == Date.today%>
        <% course.status = 'false' %>
        <%course.update!(status: 'false')%>
          <%end%>
      <tr class="odd gradeX">
        <tr>
          <td><%= course.course_name %></td>
          <td><%= course.course_description %></td>
          <td><%= course.course_validity %></td>
<!--           <td><%= course.status %></td>
 -->          <td><%= course.batch %></td>
          <td><%= course.admission_start_date %></td>
          <td><%= course.admission_end_date %></td>
          <td><%= course.fees %></td>
          <td><%= link_to 'Buy Course',new_payment_path(course), class: 'btn btn-primary' %></td>
        </tr>
        <% end %>
  </tbody>
</table>

<br>


</tr>
</tbody>
</table>
</div>
  